# currently dont have a donation link at the moment it is coming soon
github: [bubblesthedev, fnbubbles420org] # GitHub Sponsors-enabled usernames
custom: ['https://fnbubbles420.org/volunteer'] # Volunteer with fnbubbles420 org 
